src/Core/AbstractConfig.js

Now it supports such commands in VS Code as:
For Windows:
Ctrl+K, Ctrl+0 - folding all the code in file.
Ctrl+K, Ctrl+J - unfolding all the code in file.
Ctrl+Shift+[ - folding current code.
Ctrl+Shift+] - unfolding current code.
For Mac:
Cmd+K, Cmd+0 - folding all the code in file.
Cmd+K, Cmd+J - unfolding all the code in file.
Cmd+Shift+[ - folding current code.
Cmd+Shift+] - unfolding current code.
It should make better code readability.

Beautified code in Core/AbstractConfig.gs

---

src/Core/AbstractConnector.js
src/Core/AbstractPipeline.js
src/Core/AbstractStorage.js
src/Core/GoogleSheetsConfig.js
src/Core/GoogleSheetsStorage.js

Beautified code in:
Core/AbstractConnector.gs
Core/AbstractPipeline.gs
Core/AbstractStorage.gs
Core/GoogleSheetsConfig.gs
Core/GoogleSheetsStorage.gs
Now it supports such commands in VS Code as:
For Windows:
Ctrl+K, Ctrl+0 - folding all the code in file.
Ctrl+K, Ctrl+J - unfolding all the code in file.
Ctrl+Shift+[ - folding current code.
Ctrl+Shift+] - unfolding current code.
For Mac:
Cmd+K, Cmd+0 - folding all the code in file.
Cmd+K, Cmd+J - unfolding all the code in file.
Cmd+Shift+[ - folding current code.
Cmd+Shift+] - unfolding current code.
It should make better code readability.

Beautified code in other files in Core

---

src/Integrations/FacebookMarketing/Connector.js

https://github.com/OWOX/js-data-connectors/issues/40

Fix for issue #40

---

src/Integrations/OpenExchangeRates/Connector.js

Changes were inserted according to recommendations in the [issue](https://github.com/OWOX/js-data-connectors/issues/48).

Changed `value` to `default`

---

README.md
src/Integrations/Criteo/GETTING_STARTED.md
src/Integrations/Criteo/README.md

Edited README file and started to add documentation for Criteo connector.

Documentation and updates

---

src/Integrations/TikTokAds/CREDENTIALS.md
src/Integrations/TikTokAds/Code.gs
src/Integrations/TikTokAds/Connector.js
src/Integrations/TikTokAds/FieldsSchema.js
src/Integrations/TikTokAds/GETTING_STARTED.md
src/Integrations/TikTokAds/Pipeline.js
src/Integrations/TikTokAds/README.md

- Implemented the TikTok Ads Connector to import advertising data into Google Sheets.
- Added functionality for importing advertiser information, campaigns, ad groups, ads, performance metrics, and custom audiences.
- Included scheduling options for daily and hourly data refreshes.
- Created comprehensive documentation including setup instructions, authentication guide, and available data types.
- Introduced error handling and data cleanup features for improved reliability.

Add TikTok Ads Connector integration

---

src/Integrations/FacebookMarketing/Connector.js
src/Integrations/FacebookMarketing/MarketingAPIReference/FieldsSchema.js

- Set limit to Facebook Marketing API endpoints where it is missed

Standardize API limits for Facebook endpoints

---

src/Core/GoogleSheetsConfig.js
src/Integrations/LinkedIn/Code.gs
src/Integrations/LinkedIn/Connector.js
src/Integrations/LinkedIn/Constants/CommonConstants.js
src/Integrations/LinkedIn/Helper.js
src/Integrations/LinkedIn/LinkedInPagesAPIReference/LinkedInPagesFieldsSchema.js
src/Integrations/LinkedIn/LinkedInPagesAPIReference/followerStatisticsFields.js
src/Integrations/LinkedIn/LinkedInPagesAPIReference/followerStatisticsTimeBoundFields.js
src/Integrations/LinkedIn/Pipeline.js
tools/oa-update-apps-scripts.sh

New LinkedIn integration with support for:
- LinkedIn Pages API integration
- Data fetching for follower_statistics and follower_statistics_time_bound

LinkedIn pages connector v1.0.0

---

src/Core/AbstractStorage.js
src/Integrations/TikTokAds/Pipeline.js

This PR simplifies the TikTokAdsPipeline implementation and fixes a bug with ad insights data duplication.
Changes:
- Remove redundant getDateRange and getStartDateAndDaysToFetch methods
- Use AbstractPipeline's getStartDateAndDaysToFetch implementation
- Simplify startImportProcessOfTimeSeriesData by removing endDate
- Add addMissingFieldsToData for consistent data structure
- Fix bug with duplicating data for ad insights by using proper date handling

Simplify TikTokAdsPipeline date handling and fix ad insights data duplication

---

GUIDELINE.md
src/Constants/CommonConstants.js
src/Core/AbstractConnector.js
src/Core/EnvironmentAdapter.js
src/Core/GoogleBigQueryStorage.js
src/Core/GoogleSheetsConfig.js
src/Integrations/BankOfCanada/.claspignore
src/Integrations/BankOfCanada/Connector.js
src/Integrations/FacebookMarketing/.claspignore
src/Integrations/FacebookMarketing/Connector.js
src/Integrations/FacebookMarketing/Pipeline.js
src/Integrations/LinkedIn/.claspignore
src/Integrations/OpenExchangeRates/.claspignore
src/Integrations/OpenExchangeRates/Connector.js
src/Integrations/OpenHolidays/Connector.js
src/Integrations/TikTokAds/.claspignore
src/Integrations/TikTokAds/Connector.js
src/Integrations/TikTokAds/Pipeline.js
src/Integrations/TikTokAds/TiktokMarketingApiProvider.js
src/Integrations/XAds/.claspignore
src/Integrations/XAds/Connector.js
src/Integrations/XAds/Pipeline.js

- Added EnvironmentAdapter class to provide a consistent interface for Google Apps Script and Node.js operations.
- Implemented methods for environment detection, HTTP requests, date formatting, UUID generation, and more.
- Updated existing code to utilize EnvironmentAdapter for date formatting and sleep functionality, enhancing cross-platform compatibility.
- Created a comprehensive guidelines document detailing the usage and features of the EnvironmentAdapter.

introduce EnvironmentAdapter for unified environment handling

---

packages/connectors/src/Sources/BingAds/BingAdsAPIReference/BingAdsFieldsSchema.js
packages/connectors/src/Sources/BingAds/BingAdsAPIReference/adPerformanceReportFields.js
packages/connectors/src/Sources/BingAds/Connector.js
packages/connectors/src/Sources/BingAds/Helper.js
packages/connectors/src/Sources/BingAds/Source.js

- Added handling for 100MB app script limit in bulk API requests
- Implemented support for both old and new Bing Ads OAuth scopes
- Added LocationId field to ad performance reports
- Improved error handling and logging

fix: refactor Bing source logic to handle app script limits

---

apps/web/src/features/data-storage/list/components/DataStorageList/DataStorageList.tsx

Removes redundant empty state check in DataStorageList component that was blocking the UI when no storages were present. This fix enables users to create their first Data Storage without obstacles.
- Removed conditional rendering that showed "No data storages found" message
- Table component is now always visible, allowing access to create new storage functionality

fix(web): Remove redundant empty state check in DataStorageList component

---

apps/web/src/components/AppSidebar/app-sidebar.tsx
apps/web/src/features/data-marts/list/components/DataMartTable/DataMartTable.tsx
apps/web/src/features/data-marts/list/components/DataMartTable/EmptyDataMartsState.tsx
apps/web/src/features/data-storage/list/components/DataStorageList/DataStorageList.tsx
apps/web/src/shared/components/CardSkeleton/CardSkeleton.tsx
apps/web/src/shared/components/CollapsibleCard/CollapsibleCard.tsx
apps/web/src/shared/components/CollapsibleCard/CollapsibleCardHeader.tsx
packages/ui/src/styles/globals.css

- New icons in the AppSidebar
- Update dark-theme colors
- Other improvements

feat(web): New icons and dark-theme colors

---

packages/connectors/src/Sources/BingAds/CREDENTIALS.md
packages/connectors/src/Sources/FacebookMarketing/CREDENTIALS.md
packages/connectors/src/Sources/LinkedIn/CREDENTIALS.md
packages/connectors/src/Sources/OpenExchangeRates/CREDENTIALS.md
packages/connectors/src/Sources/RedditAds/CREDENTIALS.md
packages/connectors/src/Sources/XAds/CREDENTIALS.md

Created a heading for each step in the credential guides.

docs: update credential documentation for various ad sources

---

.github/workflows/deploy-docs.yml

- Update the deploy script for the custom domain

feat(docs): update deploy for custom domain

---

apps/owox/README.md

Add troubleshooting guide for MacOS/Linux installation permissions issues to `README.md`, including step-by-step nvm-based solution for proper package installation without sudo requirements.

docs(owox): add issue block to README.md

---

package.json
tools/setup-husky.mjs

- Do not overwrite the created hook if it already exists. 
- Do not run `npx husky init`, because we already do this in `npm scripts`.

feat(root): updated husky hooks creation script

---

apps/backend/src/data-marts/data-marts.module.ts
apps/backend/src/data-marts/data-storage-types/athena/services/athena-data-mart-schema.parser.ts
apps/backend/src/data-marts/data-storage-types/bigquery/services/bigquery-data-mart-schema.parser.ts
apps/backend/src/data-marts/data-storage-types/data-storage-providers.ts
apps/backend/src/data-marts/data-storage-types/facades/data-mart-schema-parser-facade.service.ts
apps/backend/src/data-marts/data-storage-types/interfaces/data-mart-schema-parser.interface.ts
apps/backend/src/data-marts/use-cases/actualize-data-mart-schema.service.ts
apps/backend/src/data-marts/use-cases/update-data-mart-schema.service.ts

Refactored Data Mart schema processing with new parser architecture for better scalability and error handling.
- **New Parser Architecture**: Added `DataMartSchemaParser` interface and `DataMartSchemaParserFacade`
- **Storage-Specific Parsers**: Implemented `AthenaDataMartSchemaParser` and `BigQueryDataMartSchemaParser`
- **Enhanced Use Cases**: 
- `UpdateDataMartSchemaService`: Integrated parser facade with improved validation
- `ActualizeDataMartSchemaService`: Added definition validation and explicit persistence
- **Better Error Handling**: Storage-specific error messages with detailed Zod validation info
- Easier addition of new storage types
- Improved validation and error reporting
- Clear separation of concerns
- Better maintainability

feat(backend): data mart schema use cases flow improved

---

.changeset/sql-validation-feature.md
apps/backend/src/data-marts/use-cases/sql-dry-run.service.ts
apps/web/src/app/api/apiClient.ts
apps/web/src/features/data-marts/edit/components/DataMartDefinitionSettings/DataMartDefinitionSettings.tsx
apps/web/src/features/data-marts/edit/components/SqlValidator/SqlValidator.tsx
apps/web/src/features/data-marts/edit/utils/definition-helpers.ts
apps/web/src/features/data-marts/shared/services/data-mart.service.ts
apps/web/src/features/data-marts/shared/types/api/request/index.ts
apps/web/src/features/data-marts/shared/types/api/request/sql-validation-request.dto.ts
apps/web/src/features/data-marts/shared/types/api/response/index.ts
apps/web/src/features/data-marts/shared/types/api/response/sql-validation-response.dto.ts
apps/web/src/hooks/use-debounce.ts
apps/web/src/shared/components/GlobalLoader/LoadingContext.tsx
apps/web/src/utils/format-bytes.ts
apps/web/src/utils/index.ts

Introducing  SQL validation for Data Marts with instant feedback to improve user experience
- 📝 **Instant validation** - Real-time SQL query checking as you type
- ❌ **Clear error messages** - User-friendly feedback when queries have issues
- 📊 **Data volume estimation** - Preview expected result size for successful queries
- ⏱️ **Automatic validation** - Seamless validation without manual triggers
- 🎯 Fewer errors when writing SQL queries
- ⚡ Faster problem detection and resolution
- 📈 Increased confidence when working with data
- 🕐 Time saved on debugging and troubleshooting
---
*This enhancement makes Data Marts more intuitive and user-friendly* 🎉

Add real-time SQL validation for Data Marts 

---

.changeset/fixes.md
.changeset/run-history-and-edit-field-in-connector.md

- added fixes section
- added "ability to edit fields" description

corrections to changset

---

.changeset/ux-improvements.md

Adds a changeset file to document UI improvements, form updates, and new planned Data Storages in the next minor version of the app.

changeset: Add changeset for upcoming minor release

---

package-lock.json
packages/connector-runner/package.json
packages/connector-runner/src/infrastructure/dependencies/npm-dependency-manager.js
packages/connector-runner/src/infrastructure/environments/nodejs-environment.js
packages/connector-runner/src/utils/package-utils.js
packages/connector-runner/test/infrastructure/dependencies/npm-dependency-manager.test.js
packages/connector-runner/test/infrastructure/environments/nodejs-environment.test.js
packages/connectors/vite.config.js

- Added minimal ordering file dependencies in the **Connector Sources** build process. In Windows, this file sorting by glob pattern is not the same as in Unix-like OS
- Fixed running NpmDependencyManager on Windows development environment
- Updated NpmDependencyManager test for Windows environment
- Refactored NpmDependencyManager class: run i/o operation in the constructor and cache results.

fix(connectors): adapt running connectors on Windows in development

---

apps/web/src/features/connectors/edit/components/ConnectorEditForm/steps/TargetSetupStep.tsx

This pull request refactors the `TargetSetupStep` component to improve code readability and maintainability by introducing a `tableName` constant and updating related logic. Additionally, it enhances the user interface text for clarity.

refactor(web): refactor text and code target setup step

---

apps/docs/astro.config.mjs

This pull request updates the configuration for https://docs.owox.com/ to reorganize and expand the structure of the documentation. The changes include adding new sections and restructuring existing ones for better organization and clarity.

fix(docs): reorganize connectors section

---

.gitattributes
.github/workflows/release-pr.yml
.markdownlint-cli2.mjs
apps/backend/CHANGELOG.md
apps/docs/astro.config.mjs
apps/docs/scripts/sync-docs.js
apps/owox/CHANGELOG.md
packages/connector-runner/CHANGELOG.md
tools/fix-changelog-headings.mjs

This pull request introduces several updates across the codebase, focusing on improving changelog consistency, integrating changelog handling into documentation workflows, and refining file processing logic. Key changes include a new script for fixing changelog headings, updates to workflows for automated changelog fixes, and adjustments to markdown processing and documentation synchronization scripts.
- **Fix Changelog Headings Script**: Added a new script `tools/fix-changelog-headings.mjs` to standardize changelog headings by appending version numbers to "Minor Changes" and "Patch Changes" sections. The script scans for `CHANGELOG.md` files, processes headings, and modifies files as needed.
- **Workflow Update**: Modified `.github/workflows/release-pr.yml` to include a step for running …

feat(docs): add changelog to the docs.owox.com

---

package-lock.json
package.json

Vulnerability detected for tmp package when using @changesets/cli

Fix tmp library vulnerability

---

.changeset/added-triggers-reports-count-columns.md
apps/backend/src/data-marts/dto/domain/data-mart.dto.ts
apps/backend/src/data-marts/dto/presentation/data-mart-response-api.dto.ts
apps/backend/src/data-marts/mappers/data-mart.mapper.ts
apps/backend/src/data-marts/use-cases/list-data-marts.service.ts
apps/web/src/features/data-marts/list/components/DataMartTable/DataMartTable.tsx
apps/web/src/features/data-marts/list/components/DataMartTable/columns/columnKeys.ts
apps/web/src/features/data-marts/list/components/DataMartTable/columns/columnLabels.ts
apps/web/src/features/data-marts/list/components/DataMartTable/columns/columns.tsx
apps/web/src/features/data-marts/list/model/mappers/data-mart-list.mapper.ts
apps/web/src/features/data-marts/list/model/types/dataMart.ts
apps/web/src/features/data-marts/shared/types/api/response/data-mart.response.dto.ts

feat(web/backend): added triggers, reports columns to Data Mart list [f-5795]

---

.changeset/bingads-user-location-report-and-csv-fix.md
packages/connectors/src/Core/EnvironmentAdapter.js
packages/connectors/src/Sources/BingAds/BingAdsAPIReference/BingAdsFieldsSchema.js
packages/connectors/src/Sources/BingAds/BingAdsAPIReference/userLocationPerformanceReportFields.js
packages/connectors/src/Sources/BingAds/Source.js

- Add user_location_performance_report node with field schema
- Refactor _fetchReportData into separate submit/poll methods for better readability
- Update ad_performance_report field descriptions and order
- Remove ReportType config parameter (now determined by schema)
- Fix CSV parsing to handle quoted fields properly in Node.js version

Bing Source Columns&Parser Errors

---

.github/workflows/release-pr.yml

This pull request improves the readability and efficiency of the `release-pr` workflow in `.github/workflows/release-pr.yml` by adding descriptive step names and ensuring that certain steps only run when there are changesets to process.

refactor(workflow): enhance readability of release PR steps

---

.changeset/optimize-logging-security.md
packages/connectors/src/Sources/BingAds/Code.gs
packages/connectors/src/Sources/CriteoAds/Code.gs
packages/connectors/src/Sources/FacebookMarketing/Connector.js
packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/FieldsSchema.js
packages/connectors/src/Sources/FacebookMarketing/Source.js
packages/connectors/src/Sources/LinkedInAds/Source.js
packages/connectors/src/Sources/LinkedInPages/Source.js
packages/connectors/src/Sources/OpenExchangeRates/Source.js
packages/connectors/src/Sources/RedditAds/Code.gs
packages/connectors/src/Sources/RedditAds/Source.js
packages/connectors/src/Sources/TikTokAds/Code.gs
packages/connectors/src/Sources/XAds/Code.gs
packages/connectors/src/Sources/XAds/Source.js
packages/connectors/src/Storages/GoogleBigQuery/GoogleBigQueryStorage.js

- Reduced log noise in BigQuery storage
- Fixed credentials exposure in Sources logs
- Added progress tracking and explicit time series flags to Facebook connector

feat: enhance BigQuery logging - remove sensitive data exposure and add progress tracking

---

packages/connectors/src/Sources/FacebookMarketing/CREDENTIALS.md

Corrected the step numbering sequence in the Facebook Ads access token instructions for better clarity and logical flow.

docs(facebook): fix step numbering

---

docs/getting-started/deployment-guide/digitalocean.md

App Platform + Managed MySQL example

Add DigitalOcean deployment documentation

---

packages/idp-better-auth/package.json

This pull request makes minor formatting changes to the `package.json` file in the `idp-better-auth` package.

chore: code format package.json
