- src/Integrations/LinkedIn/Helper.js
- src/Integrations/LinkedIn/LinkedInAdsAPIReference/adAnalyticsFields.js
- src/Integrations/LinkedIn/Pipeline.js
- Added `toSnakeCase` helper function for consistent table naming across LinkedIn integration
- Implemented automatic table prefix based on API type:
- `linkedin_ads_` for Ads API
- `linkedin_pages_` for Pages API
- Added `GoogleBigQueryPartitioned` flag for date fields to optimize BigQuery performance
> feat(LinkedIn): enhance table naming and date partitioning

- apps/web/src/components/Logo/Logo.tsx
- apps/web/src/components/Logo/index.ts
- Changed Logo component export from default to named export
- Removed unnecessary React import
- Simplified component syntax by removing React.FC type
- Updated component import in index.ts file
This change aligns with modern React practices by:
- Using named exports for better tree-shaking
- Removing redundant React import (not needed since React 17+)
- Simplifying component type definitions
> refactor(web): update Logo component export pattern 

- packages/connectors/eslint.config.js
- packages/eslint-config/node.js
@zapolsky @amarchenk0 , in #159 , I removed the `'src/**/*'` folder ignore in the ESLint configuration for connectors. It turned out that this should not have been done, because the final configuration is not yet available.
> fix(conntectors): Returned ignoring the launch of the eslinter

- apps/backend/package.json
- apps/owox/src/commands/serve.ts
After discussing with @amarchenk0, I questioned whether we needed to process signals in `owox serve`. If signal processing is removed, then `kill -2 {PID}` (SIGINT) and `kill -15 {PID}` (SIGTERM) of the main process do not terminate child processes.
In this PR, I refactored the code and fixed the bug when `owox senve` don't find `@owox/backend`. I did not remove signal handling.
> refactor(owox): updare serve

- apps/backend/.env.example
- apps/backend/package.json
- apps/backend/src/config/data-source-options.config.ts
- apps/backend/src/config/get-sqlite-database-path.ts
- package-lock.json
This PR introduces enhanced logic for determining the SQLite database file path, improving flexibility and cross-platform compatibility.
**Key Changes:**
*   **Dynamic SQLite Path Resolution:**
*   A new function `getSqliteDatabasePath` has been implemented in `apps/backend/src/config/data-source-options.config.ts`.
*   This function allows specifying the SQLite database path via the `SQLITE_DB_PATH` environment variable.
*   If `SQLITE_DB_PATH` is not set, the database will automatically be stored in the system's application data directory (e.g., `~/Library/Application Support/owox/sqlite/app.db` on macOS) using the `env-paths` library.
*   Automatically creates necessary directories if they do not exist.
*   **Configuration Updates:**
*   The `apps/backend/.env.example` file has been …
> feat(backend): added cross-platform sqlite db path

- apps/web/src/features/data-marts/list/components/DataMartTable/DataMartActionsCell.tsx
- apps/web/src/features/data-marts/list/components/DataMartTable/DataMartTable.tsx
- apps/web/src/features/data-marts/list/components/DataMartTable/EmptyDataMartsState.tsx
- apps/web/src/features/data-marts/list/components/DataMartTable/SortableHeader.tsx
- apps/web/src/features/data-marts/list/components/DataMartTable/ToggleColumnsHeader.tsx
- apps/web/src/features/data-marts/list/components/DataMartTable/columns.tsx
- apps/web/src/pages/data-marts/list/DataMartsPage.tsx
- apps/web/src/shared/components/CardSkeleton/CardSkeleton.tsx
- apps/web/src/shared/components/CardSkeleton/index.ts
- packages/ui/src/styles/globals.css
This pull request includes a series of UI and UX improvements for the Data Marts list page:
- New layout and styling for the table and page elements.
- Empty state component for better user guidance when no Data Marts exist.
- Loading state with skeleton component to improve perceived performance.
- Responsive layout improvements for better display on different screen sizes.
- Refined action cell menu behavior for a more intuitive user experience.
- Column visibility management with a new toggle component for flexible table views.
All changes focus on improving visual consistency, responsiveness, and usability across the page.
> feat(web): Improve UI and UX of Data Marts List Page

- apps/owox/CONTRIBUTING.md
- apps/owox/PUBLISHING.md
- apps/owox/README.md
This commit addresses various Markdown linting issues across `CONTRIBUTING.md` and `README.md`. It primarily focuses on correcting heading hierarchy, specifying languages for code blocks, and standardizing list formatting to improve document clarity and adherence to style guidelines.
> docs(owox): updated docs with linter rules

- apps/docs/astro.config.mjs
- apps/docs/scripts/env-config.js
- apps/docs/scripts/sync-docs.js
- apps/docs/scripts/utils.js
- Add a trailing slash to the astro.config.mjs (now all URLs will end with "/" )
- Update the strategy for creating a link path from relative to root-relative (which fixes some problems with site page URLs )
> feat(docs): add trailing slash to the astro config

- apps/backend/.env.example
- apps/backend/src/common/logger/logger.service.ts
- **Logger Service**: Added support for configurable log levels via `LOG_LEVELS` environment variable
- **Default Behavior**: Changed default log levels to `log`, `warn`, `error` (previously included all levels)
- **Configuration**: 
- `LOG_LEVELS` accepts comma-separated values (e.g., `log,warn,error,debug`)
- Falls back to defaults with warning if invalid levels provided
- Validates against NestJS supported levels: `log`, `error`, `warn`, `debug`, `verbose`, `fatal`
```bash
LOG_LEVELS=log,warn,error,debug
LOG_LEVELS=log,warn,error,debug,verbose
```
⚠️ **Default log output now excludes `debug` and `verbose` levels.** Set `LOG_LEVELS=log,error,warn,debug,verbose,fatal` to restore previous behavior.
> feat(backend): add configuration of log levels

- packages/connectors/vite.config.js
- Fix "ReferenceError: processShortLinks is not defined" that is cased by adding Utils folder inside Core folder
> fix: utils in self-hosted version are not included in build

- apps/backend/src/config/express-static.config.ts
Fix static file serving: use Express 'root' option for index.html
Previously, the server attempted to serve the SPA entry point using an absolute path with res.sendFile(join(distPath, 'index.html')), which could fail due to path resolution issues across environments. This PR switches to res.sendFile('index.html', { root: distPath }), leveraging Express's built-in path resolution. This ensures consistent and reliable serving of index.html for client-side routes, fixing the 404 error on page reload.
> fix(backend): update static configurations

- apps/backend/src/data-marts/data-storage-types/bigquery/services/bigquery-data-mart-schema.provider.ts
- apps/backend/src/data-marts/data-storage-types/bigquery/services/bigquery-report-reader.service.ts
- apps/web/src/features/data-marts/edit/components/DataMartSchemaSettings/tables/BaseSchemaTable.tsx
- apps/web/src/features/data-marts/edit/components/DataMartSchemaSettings/tables/BigQuerySchemaTable.tsx
**What was fixed:**
- Correct handling of record fields in BigQuery data mart schema editor
- Fixed schema handling for connector-defined data marts
**Affected components:**
- Backend: BigQuery schema provider and report reader services
- Frontend: schema table components (BaseSchemaTable, BigQuerySchemaTable)
This fix ensures stable operation of the schema editor when working with nested data structures and connector-defined data marts.
> fix: record fields in data mart schema editor, schema for connector

- apps/web/src/features/connectors/edit/components/ConnectorDefinitionField/ConnectorConfigurationItem.tsx
- apps/web/src/features/data-marts/edit/components/DataMartDefinitionSettings/form/ConnectorDefinitionField.tsx
- apps/web/src/features/data-marts/edit/components/DataMartDetails.tsx
- apps/web/src/features/data-marts/scheduled-triggers/components/ScheduledTriggerForm/FormDescriptions/ReportSelectionDescription.tsx
- apps/web/src/features/data-marts/scheduled-triggers/components/ScheduledTriggerForm/FormDescriptions/TriggerTypeOptionsDescription.tsx
Improved UI and text clarity in the Data Mart page: updated the Connector block layout, polished the dropdown menu, and refreshed descriptions.
> feat(web): Refine the Data Mart Page (Layout, Menu, and Texts)

- packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/FieldsSchema.js
- packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/ad-account-fields.js
- packages/connectors/src/Sources/FacebookMarketing/MarketingAPIReference/ad-account-user-fields.js
All unnecessary and unimplemented fields are commented out.
> fix: comment out unimplemented fields in Facebook Marketing API schemas

- packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/adCampaignFields.js
- packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/creativesFields.js
The `versionTag` field was removed from `adCampaignFields`, and the `inlineContent` field was removed from `creativesFields`. No functional changes to data processing or API integration are introduced in this update.
> refactor(LinkedInAds): remove unused fields

- packages/connectors/src/Sources/TikTokAds/Source.js
Mark App ID and App Secret as required fields so users won't miss them and avoid the `Error fetching advertiser for advertiser 7504697128674066433: To fetch advertiser data, both AppId and AppSecret must be provided` issue.
> feat(TikTokAds): mark App ID and App Secret as required fields

- .changeset/destination-cards-in-destination-tab.md
- apps/web/src/features/data-destination/edit/components/DataDestinationEditForm/FormDescriptions/LookerStudioJsonConfigDescription.tsx
- apps/web/src/features/data-marts/reports/edit/components/GoogleSheetsReportEditForm/GoogleSheetsReportEditForm.tsx
- apps/web/src/features/data-marts/reports/edit/components/GoogleSheetsReportEditSheet/GoogleSheetsReportEditSheet.tsx
- apps/web/src/features/data-marts/reports/edit/components/LookerStudioReportEditForm/LookerStudioReportEditForm.tsx
- apps/web/src/features/data-marts/reports/edit/components/LookerStudioReportEditSheet/LookerStudioReportEditSheet.tsx
- apps/web/src/features/data-marts/reports/edit/hooks/useGoogleSheetsReportForm.ts
- apps/web/src/features/data-marts/reports/edit/hooks/useLookerStudioReportForm.ts
- apps/web/src/features/data-marts/reports/list/components/GoogleSheetsActionsCell/GoogleSheetsActionsCell.tsx
- apps/web/src/features/data-marts/reports/list/components/GoogleSheetsReportsTable/GoogleSheetsReportsTable.tsx
- apps/web/src/features/data-marts/reports/list/components/LookerStudioActionsCell/LookerStudioActionsCell.tsx
- apps/web/src/features/data-marts/reports/list/components/LookerStudioReportsTable/LookerStudioReportsTable.tsx
- apps/web/src/features/data-marts/reports/list/components/columns/columns.tsx
- apps/web/src/features/data-marts/reports/shared/components/DestinationCard/DestinationCard.tsx
- apps/web/src/features/data-marts/reports/shared/components/DestinationCard/index.ts
- apps/web/src/features/data-marts/reports/shared/components/EmptyDataMartDestinationsState/EmptyDataMartDestinationsState.tsx
- apps/web/src/features/data-marts/reports/shared/components/EmptyDataMartDestinationsState/index.ts
- apps/web/src/features/data-marts/reports/shared/components/index.ts
- apps/web/src/features/data-marts/reports/shared/index.ts
- apps/web/src/features/data-marts/reports/shared/model/context/reducer.ts
- apps/web/src/features/data-marts/reports/shared/model/context/types.ts
- apps/web/src/features/data-marts/reports/shared/model/hooks/index.ts
- apps/web/src/features/data-marts/reports/shared/model/hooks/useColumnVisibility.ts
- apps/web/src/features/data-marts/reports/shared/model/hooks/useReport.ts
- apps/web/src/pages/data-marts/edit/DataMartDestinationsContent.tsx
- apps/web/src/shared/components/CollapsibleCard/CollapsibleCardHeaderTitle.tsx
- packages/ui/src/components/common/copyable-field.tsx
This update changes the Destination tab to display a separate card for each specific destination in the project, instead of grouping reports by destination type.
- Shows **one card per destination**, making the layout more granular and clear.  
- Each card lists **only the reports** that belong to that specific destination.  
- Updated data fetching to retrieve the full destinations list and filter reports by destination ID.  
To provide a clearer, more organized view of destinations, making it easier for users to locate and manage reports tied to specific destinations.
> Feat(Web): Destination tab updates

- .changeset/split-linkedin-daterange-fields.md
- packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/LinkedInAdsFieldsSchema.js
- packages/connectors/src/Sources/LinkedInAds/LinkedInAdsAPIReference/adAnalyticsFields.js
- packages/connectors/src/Sources/LinkedInAds/Source.js
- packages/connectors/src/Sources/LinkedInPages/Source.js
- Replace single dateRange field with separate dateRangeStart and dateRangeEnd fields for better data granularity
- Remove MaxFieldsPerRequest param and hardcode the value
> Split LinkedIn dateRange fields and hardcode field limits

- .prettierignore
- packages/idp-owox/package.json
Update the path for the `.prettierignore` file in the format scripts to ensure proper formatting checks and application. Additionally, include the `.astro` directory in the `.prettierignore` file.
> chore: update code format scripts in package.json 

- apps/backend/src/data-marts/entities/report-data-cache.entity.ts
- apps/backend/src/migrations/1756904880000-add-cascade-to-report-data-cache-fk.ts
- Cascade delete report_data_cache on report removal.
- Add migration (SQLite/MySQL) to recreate FK with ON DELETE CASCADE and ensure index on reportId.
- Align entity: onDelete: 'CASCADE', explicit JoinColumn name (reportId), and index.
- Fixes FK constraint error; related cache rows are removed automatically when a report is deleted.
- apps/backend/src/migrations/1756904880000-add-cascade-to-report-data-cache-fk.ts
> fix(backend): report delete no longer fails due to cache FK

- apps/web/package.json
- package.json
- tools/format-package-info.mjs
This pull request introduces an automated script to format `package.json` files for all fixed-versioned packages, improving the consistency and maintainability of package metadata formatting across the repository. The main change replaces the previous hardcoded list of files for formatting with a dynamic approach that discovers relevant packages using the changeset configuration. Minor formatting updates are also made in some workspaces.
**Automated formatting for package metadata:**
- Added a new script `tools/format-package-info.mjs` that automatically discovers all fixed-versioned packages (as defined in `.changeset/config.json`) and formats their `package.json` files using Prettier. The script supports both formatting and check modes.
- Updated the root `package.json` to use the new …
> refactor: streamline package.json formatting for release pr

- .changeset/increase-timeout-configuration.md
- apps/backend/src/bootstrap.ts
- apps/backend/src/common/middleware/operation-timeout.middleware.ts
- apps/backend/src/data-marts/data-marts.module.ts
- apps/web/src/features/data-marts/shared/services/data-mart.service.test.ts
- apps/web/src/features/data-marts/shared/services/data-mart.service.ts
- Increased server timeout settings to 180 seconds for better handling of long-running requests.
- Implemented middleware for operation timeouts in the DataMartsModule, applying different timeout values for specific routes.
- Updated DataMartService methods to include timeout configurations for API requests.
> feat: Increase timeout for SQL validation up to 3 min

- apps/backend/src/config/migrations.config.ts
Acquires a distributed lock for running migrations to prevent multiple instances from running the same migration simultaneously. Known TypeORM [issue](https://github.com/typeorm/typeorm/issues/4588) with multiple instances.
1. Attempts to create a temporary lock table `__migrations_lock__`
2. If table creation succeeds - lock is acquired, migration can proceed
3. If table already exists - another instance is running migrations, wait and retry
4. After migration completes - lock table is dropped to release the lock
- Service 0 creates lock table and runs migrations
- Services 1-9 wait until lock table is dropped
- After lock release, services 1-9 check migration status and skip already completed ones
- If for some reason the `__migrations_lock__` table is not deleted, you will need to do …
> feat(backend): make migration handling for multiple instances

- apps/backend/src/config/migrations.config.ts
```
Sep 16 13:47:29
query failed: CREATE TABLE __migrations_lock__ (id INTEGER)
Sep 16 13:47:29
error: Error: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
```
> fix(backend): add primary key to migrations lock table for MySQL compatibility

- apps/backend/src/migrations/1758720208111-rename-bing-ads-connector-to-microsoft-ads.ts
This pull request introduces a database migration to update the naming of a connector in the `data_mart` table. The migration ensures consistency by renaming "BingAds" to "MicrosoftAds" and provides a rollback option.
> feat(migration): rename Bing Ads connector to Microsoft Ads

- packages/connectors/src/Sources/LinkedInAds/Source.js
- packages/connectors/src/Sources/LinkedInPages/Source.js
Deleted API version from connector configuration and set the LinkedIn-Version header to 202509 in both LinkedIn Ads and LinkedIn Pages sources.
> fix(LinkedIn): Remove API version config and hardcode LinkedIn-Version header

- apps/backend/src/migrations/1758809780933-rename-bing-ads-connector-to-microsoft-ads-for-all-db.ts
This pull request adds a new migration to update connector names in the database for consistency. Specifically, it renames all instances of "BingAds" to "MicrosoftAds" in the `data_mart` table for connector definitions, and provides a way to revert this change if needed.
> feat(migration): add migration to rename bing ads connector to microsoft ads, again

- packages/idp-better-auth/src/providers/better-auth-provider.ts
- packages/idp-owox/src/config.ts
- packages/idp-owox/src/owoxIdp.ts
- packages/idp-protocol/README.md
- packages/idp-protocol/src/middleware/protocol-middleware.ts
- packages/idp-protocol/src/providers/null-provider.ts
- packages/idp-protocol/src/types/provider.ts
- Introduced `signUpMiddleware` in `IdpProvider` for handling user registration requests.
- Updated `ProtocolRoute` and middleware registration to include `/sign-up` route.
- Enabled sign-up functionality for `owox` IDP provider.
- Refactored URL redirection logic for auth endpoints.
> feat: Add sign-up middleware support to IDP providers

- packages/connectors/src/Storages/AwsAthena/AwsAthenaStorage.js
- Fix this error: Query FAILED: TYPE_MISMATCH: line 3:21: Cannot apply operator: date = varchar
> fix: fix AWS Athena error with types

- apps/backend/src/data-marts/controllers/connector.controller.ts
- packages/idp-better-auth/src/providers/better-auth-provider.ts
- packages/idp-better-auth/src/services/token-service.ts
This pull request updates how user roles are handled and injected into authentication tokens in the Better Auth provider. The most important changes are the addition of a dependency on `UserManagementService` in `TokenService`, and the dynamic assignment of user roles in token payloads based on database values rather than hardcoded roles.
**User role management and token payloads:**
- `TokenService` now depends on `UserManagementService` to retrieve user roles dynamically, instead of assigning a hardcoded `'admin'` role. The user’s actual role is fetched from the database and included in the token payload if available.
**Service initialization order and dependencies:**
- In `BetterAuthProvider`, `UserManagementService` is now initialized before `TokenService`, and passed as a dependency …
> fix(idp-better-auth): fix viewer role
